@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user,"Customer","Пользователь")

Container(webApp,"Web Application","SPA")
Container(mobApp,"Mobile Application","iOS/Android")

System_Boundary(wh,WarmHouse){
    Container(gw, "API Gateway")

    ContainerQueue(rm,RabbitMq)

    Container(ia,"Identity & Access","Управление пользователями и доступами")
    Container(hh,"Household","Управление домом")
    Container(tm,Telemetry,Приём и хранение телеметрии и событий от устройств)
    Container(re, Rules Engine,Управление сценариями и их выполнение)
    Container(dm,"Device Managment",Управление устройствами)

    Rel_Left(gw,ia,HTTP)
    Rel_Down(gw,hh,HTTP)
    Rel_Down(gw,dm,HTTP)
    Rel_Down(gw,tm,HTTP)
    Rel_Down(gw,re,HTTP)

'    Rel_R(re,hh,HTTP,Ин-ия о доме)
'    Rel_R(re,dm,HTTP,Ин-ия об устройствах)

    Container(ntf,Notifications,Доставка пользовательских уведомлений)
    Container(sh,Scheduler,"Сервис выполнение периодических команд")

    Container_Boundary(db,Postrges Instance){
        ContainerDb(ia_db, I&A)
        ContainerDb(hh_db, Household)
        ContainerDb(re_db, Rules)
        ContainerDb(dm_db, "Device")
    }

    ContainerDb(ch_tl, ClickHouse Telemetry)

    'Postrges Rels
    Rel(ia,ia_db,SQL)
    Rel(hh,hh_db,SQL)
    Rel(re,re_db,SQL)
    Rel(dm,dm_db,SQL)

    Rel(tm,ch_tl,SQL)

    'RabbitMq Rels
    Rel(ntf,rm,SUB,notif)
    Rel(re,rm,SUB,rules_exec)
    Rel(dm,rm,PUB,device_tl)
    Rel(tm,rm,SUB,device_tl)

    Rel(tm,rm,PUB,notif)

    Rel(re,sh,HTTP,Комнады запуска сценариев)
    Rel(sh,rm,PUB,rules_exec)
}

Rel(user,webApp,"UI")
Rel(user,mobApp,"UI")
Rel(webApp,gw,"HTTP")
Rel(mobApp,gw,"HTTP")




System_Ext(extDev,"External Smart Devices"){
    Container_Ext(heating,"Heating Controller")
    Container_Ext(light,"Light Controller")
    Container_Ext(door,"Door Controller")
    Container_Ext(shd,"Smart Home Devices")
}

System_Ext(notifProvider,"Notification Provider"){
    Container_Ext(smsNotif,"SMS")
    Container_Ext(tgNotif,"Telegram")
    Container_Ext(emailNotif,Email)
}
Rel(ntf,notifProvider,HTTP/SMTP)

Rel(dm,extDev,HTTP/WebSocket)

'System_Ext(extDev,"External Smart Devices")

'    Container_Boundary(dm,"Device Managment",Управление устройствами){
'        Container(do,"Device Onboarding ","Подключение устройства")
'        Container(dg,"Device GateWay","Интеграционный слой управления устройствами")
'        Container(dr,"Device Registry","Управление устройствами дома")
'    }

'    Container_Boundary(dm,"Device Managment",Управление устройствами){
'        Container(do,"Device Onboarding ","Подключение устройства")
'        Container(dg,"Device GateWay","Интеграционный слой управления устройствами")
'        Container(dr,"Device Registry","Управление устройствами дома")
'    }
@enduml