@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user,"Customer","Пользователь")

System(wh, "WarmHouse","Управление умным домом")
'System_Boundary(c1,WarmHouse){
'    System(um,"User Management")
'    System(dm,"Device Management")
'    System(sm,"Scenario Management")
'}

System_Ext(devices,"Smart Devices","Устройства умного дома")

Rel(wh,devices,"df")
Rel(user,wh,"Управление умным домом посредством нашей системы")

'Rel(dm,devices,"Управление")
'Rel(user,c1,"Взаимодействую")
'Rel(sm,dm,"Управление и мониторинг")
@enduml